export const metadata={title:'Strategic Consulting, Event Production & Organizational Systems',description:'CG Enterprises, led by Charmin Greene, provides strategic consulting, live event production and organizational systems for mission-driven organizations.',alternates:{canonical:'/'},openGraph:{title:'CG Enterprises | Strategy, Experiences & Impact',description:'Strategic consulting, event production and organizational systems led by Charmin Greene.',url:'/'}};
const services = [
  { title: "Strategic Consulting", desc: "Clarity, strategy and solutions for complex challenges.", image: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=1000&q=85" },
  { title: "Event Production", desc: "Extraordinary experiences designed to inspire action.", image: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=1000&q=85" },
  { title: "Organizational Systems", desc: "People, processes and structures built for what comes next.", image: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=1000&q=85" },
];
const sectors = ["Media & Live Events", "Government", "Philanthropy", "Social Impact"];
export default function Home() {
  return <>
    <main>
      <section className="hero">
        <div className="heroCopy"><p className="eyebrow">VISION INTO IMPACT <span className="rule"/></p><h1>STRATEGY<br/>FOR A BRIGHTER<br/>TOMORROW.</h1><p className="lead">We help mission-driven organizations, brands and changemakers bring bold ideas to life through strategic consulting, event production and organizational systems.</p><a className="goldButton" href="/expertise">EXPLORE OUR EXPERTISE <span>→</span></a></div>
        <div className="heroImage" role="img" aria-label="Sunlit architectural interior"><span className="heroAside">PEOPLE<br/>IDEAS<br/>PARTNERSHIPS<br/>EXPERIENCES<br/>LASTING CHANGE</span></div>
      </section>
      <section className="expertise" aria-labelledby="expertise-heading"><div className="sectionIntro"><h2 id="expertise-heading">Thoughtful strategy.<br/><em>Exceptional execution.</em></h2></div><div className="serviceGrid">{services.map(s => <a href={"/expertise/"+({"Strategic Consulting":"strategic-consulting","Event Production":"event-production","Organizational Systems":"organizational-systems"} as Record<string,string>)[s.title]} className="service" key={s.title}><div className="serviceImage" style={{backgroundImage:`url("${s.image}")`}} role="img" aria-label={s.title}/><h3>{s.title}</h3><p>{s.desc}</p></a>)}</div></section>
      <section className="leadershipStrip"><div><h2>Meet Charmin Greene.</h2><p>Discover the leadership behind CG Enterprises and the thoughtful approach guiding every engagement.</p><a className="textLink" href="/leadership">MEET OUR LEADERSHIP ↗</a></div><div className="leadershipStripMark" aria-hidden="true">CG</div></section><section className="statement"><h2>Where vision meets <em>the ability to deliver.</em></h2><p>We connect strategic thinking with exceptional execution, helping organizations create meaningful experiences and sustainable impact.</p><a className="textLink" href="/about">DISCOVER OUR APPROACH ↗</a></section>
      <section id="sectors" className="sectors"><div><h2>Impact beyond<br/><em>boundaries.</em></h2></div><div className="sectorList">{sectors.map(name=><div key={name} className="sectorText"><strong>{name}</strong></div>)}</div></section>
      <section className="journalTeaser"><h2>Ideas worth<br/><em>exploring.</em></h2><p>Read our original perspectives on strategy implementation, audience-centered experiences and effective organizational systems.</p><a className="textLink" href="/journal">VISIT THE JOURNAL ↗</a></section><section className="boutique"><div className="boutiqueImage" role="img" aria-label="Curated boutique lifestyle vignette"/><div className="boutiqueCopy"><p className="eyebrow">THE CG EDIT / BOUTIQUE BY CHARMIN</p><h2>Beauty<br/>with purpose.</h2><p>A curated shopping experience for a more intentional life. Discover the collection through our Etsy boutique.</p><a className="goldButton" href="https://www.etsy.com/shop/BoutiqueByCharmin" target="_blank" rel="noopener noreferrer">EXPLORE THE BOUTIQUE <span>↗</span></a><small>Purchases are completed securely on Etsy.</small></div></section>
      <section className="contact" id="contact"><div><p className="eyebrow">LET'S BUILD WHAT'S NEXT</p><h2>A more impactful<br/><em>tomorrow is possible.</em></h2><p>Tell us what you're building and let's start a conversation.</p></div><div className="contactPanel"><p>Whether you have a clearly defined project or an idea in its earliest stages, we'd love to learn more.</p><a className="goldButton" href="/contact">START YOUR INQUIRY ↗</a></div></section>
    </main>
  </>;
}